apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Checkout test
on:
  workflow_dispatch:
jobs:
  checkout:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout/.cloudbees/testing
